### ISSUE TITLE
Missing withCredentials

### ISSUE THREAD

**Issue by okiru** [jonhoo/vast-vmap#6]
The XHR is missing the `withCredentials` flag. This is easily remedied by setting it in `fetchXML()`:
```
  var request = new XMLHttpRequest();
  request.withCredentials = true;
```
Without `withCredentials`, some advertisers' (e.g., doubleclick) servers would not respond properly.

**Comment by Fire-Brand** [comment]
tried to add it myself as @okiru mentioned but got an Error saying:
``` A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'null' is therefore not allowed access.```
any idea why?

**Comment by jonhoo** [comment]
How did you run the file? For CORS to work correctly, I think you need to open the file using `http://` or `https://`, not using `file://`.

**Comment by Fire-Brand** [comment]
well, right now i'm running locally, so maybe that's why...

**Comment by jonhoo** [comment]
That's probably why. Try using a local web server, or upload it somewhere and try it there.

**Comment by shlomitc** [comment]
I also tried to it in my code, running on a local server (http), but got the same error Fire-Brand got.

Unless Access-Control-Allow-Origin specifies the specific domain, it won't work.

It fails in the `fetchXML()` function, because of status code 0.
Maybe we should add an exception for this status code?

**Comment by juanparati** [comment]
I discovered that many Ad providers like Rubicon or Serving-sys are not allowing CORS with credentials. The reason is that those add providers are not sending the header "Access-Control-Allow-Credentials".

In order to accept CORS request with credentials is required that Ad server should provide at least one of the following headers:
- Access-Control-Allow-Origin with the specific domain name (wildcard is not allowed)
- Access-Control-Allow-Credentials: true

It seems that many Ad providers do not send any of those headers. In case of the Access-Control-Allow-Origin it could be impossible to use it for them, because those Ad providers can be requested thought a wrapper redirection and they don't know which domains are allowed. The best solution for the Ad providers is just to send the "Access-Control-Allow-Credentials" header with value "true" (For example Smartclip Ad provider is doing that).

The reason why many Ad providers do not allow CORS request with credentials are:
1) Policy reasons (European cookie law issues) 
2) They are only serving to VAST Flash implementations that are not affected by CORS limitations, so they are not aware that HTML5 video is coming (Well, it is still here from time ago).

What I recommend, is to keep the "withCredentials" option deactivated by default and then to provide a configuration parameter like:

withcredentials = false (Default)
withcredentials = first (With credentials is used in the first request but not in the following wrapper redirections)
withcredentaisl = true (Always request with credentials)

The reason why I recommend to have the option "withcredentials=first" is because many main Ad providers require to pass those cookies, so if you are 100% sure that your main/first Ad provider will require pass those cookies, then you can use this option without the risk of break the Ad extraction process when a wrapper redirection is found, and another request against an unknown third party Ad provider is performed.

**Comment by jonhoo** [comment]
#34 should let you fix this yourself on a case-by-case basis.

**Comment by sterpe** [comment]
@juanparati:  If you have a specific example request where a Rubicon Project server is not returning appropriate CORS headers, we can look into it.

Thanks.

**Comment by juanparati** [comment]
Hi Sterpe, I cannot experience CORS issues with Rubicon, but yes with Serving-sys.

**Comment by sterpe** [comment]
I don't work for Serving-sys, but do let us know anout any issues you encounter with tRP.
